spring.application.name=QuickDrop

spring.datasource.url=jdbc:postgresql://localhost:5432/quickdrop
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# your custom limit (service-level validation)
app.file.max-size=26214400

# IMPORTANT: spring/tomcat level limit (actual fix)
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

app.base-url=http://54.79.58.55

app.cleanup.cron=0 */10 * * * *